import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import useEffectiveColorScheme from '../../hooks/useEffectiveColorScheme';

const palettes = {
  light: {
    screen: '#FFFFFF',
    surface: '#FFFFFF',
    canvas: '#FFFFFF',
    title: '#141414',
    muted: '#64748B',
    mutedStrong: '#6B7280',
    subtle: '#667085',
    divider: 'rgba(0, 0, 0, 0.1)',
    border: 'rgba(0, 0, 0, 0.1)',
    inputBackground: '#F8FAFC',
    inputBorder: 'rgba(0, 0, 0, 0.1)',
    tileBackground: '#F7F8FA',
    tileBackgroundActive: '#F8F6FF',
    tileBorder: '#E4E7EC',
    heroStart: '#635BFF',
    heroEnd: '#A720FF',
    primary: '#635BFF',
    primaryText: '#FFFFFF',
    chipBg: '#FAFAFB',
    chipIndex: '#7C8AA5',
    warningBg: '#FFF9EB',
    warningBorder: '#F7D76A',
    warningText: '#B45309',
    switcherBackdrop: 'rgba(244, 245, 247, 0.8)',
    switcherShadow: '#7C3AED',
    tokenBadgeBg: '#EFEFEF',
  },
  dark: {
    screen: '#111214',
    surface: '#181A1E',
    canvas: '#111214',
    title: '#F5F7FA',
    muted: '#A8B0C2',
    mutedStrong: '#C6CDD9',
    subtle: '#98A2B3',
    divider: 'rgba(255, 255, 255, 0.12)',
    border: 'rgba(255, 255, 255, 0.12)',
    inputBackground: '#1D2128',
    inputBorder: 'rgba(255, 255, 255, 0.16)',
    tileBackground: '#1D2128',
    tileBackgroundActive: '#252A36',
    tileBorder: 'rgba(255, 255, 255, 0.12)',
    heroStart: '#6A61FF',
    heroEnd: '#B23BFF',
    primary: '#6A61FF',
    primaryText: '#FFFFFF',
    chipBg: '#1A1E25',
    chipIndex: '#9AA5B5',
    warningBg: '#2A2211',
    warningBorder: '#8F6A00',
    warningText: '#F7C86A',
    switcherBackdrop: 'rgba(9, 11, 15, 0.82)',
    switcherShadow: '#6A61FF',
    tokenBadgeBg: '#262B33',
  },
};

const buildStyles = (scheme: 'light' | 'dark') => {
  const p = palettes[scheme];

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: p.screen,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 28,
    },
    title: {
      color: p.title,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '700',
      marginBottom: 8,
    },
    subtitle: {
      color: p.muted,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 18,
    },
    helper: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 8,
      marginBottom: 12,
    },
    error: {
      color: '#EF476F',
      fontSize: 14,
      lineHeight: 20,
      marginTop: 8,
      marginBottom: 12,
    },
    actionButton: {
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionButtonDanger: {
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: '#C53964',
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionButtonSecondary: {
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: p.surface,
      borderWidth: 1,
      borderColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionText: {
      color: p.primaryText,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    actionTextSecondary: {
      color: p.primary,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    input: {
      minHeight: 50,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: p.inputBorder,
      backgroundColor: p.inputBackground,
      paddingHorizontal: 12,
      paddingVertical: 12,
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 16,
    },
    row: {
      backgroundColor: p.surface,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderWidth: 1,
      borderColor: p.border,
      marginBottom: 12,
    },
    rowDivider: {
      height: 1,
      backgroundColor: p.divider,
    },
    rowTitle: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    rowSubTitle: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 4,
    },
    rowValue: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '700',
      marginTop: 6,
    },
    txAmountPositive: {
      color: '#16A34A',
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '700',
      marginTop: 6,
    },
    txAmountNegative: {
      color: '#E11D48',
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '700',
      marginTop: 6,
    },
    homeHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    homeAccountButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 0,
      paddingHorizontal: 0,
    },
    homeSettingsButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeAddressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      alignSelf: 'flex-start',
      marginBottom: 8,
    },
    homeAddressText: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
      fontFamily: 'monospace',
    },
    homeAccountText: {
      color: p.subtle,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    homeHeaderIcon: {
      color: p.subtle,
      fontSize: 14,
      fontWeight: '500',
    },
    homeAddressIcon: {
      color: p.subtle,
      fontSize: 14,
      fontWeight: '400',
    },
    homeHeaderDivider: {
      height: 1,
      backgroundColor: p.divider,
      marginHorizontal: -16,
      marginBottom: 16,
    },
    homeHeroCard: {
      borderRadius: 16,
      padding: 24,
      marginBottom: 24,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: p.primary,
    },
    homeHeroGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    homeHeroLabel: {
      color: '#FFFFFF',
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
      marginBottom: 8,
    },
    homeHeroValue: {
      color: '#FFFFFF',
      fontSize: 36,
      lineHeight: 40,
      fontWeight: '700',
      marginBottom: 0,
    },
    homeHeroCurrency: {
      color: '#FFFFFF',
      fontSize: 18,
      lineHeight: 28,
      fontWeight: '400',
    },
    sectionTitle: {
      color: p.subtle,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
      letterSpacing: 0.35,
      textTransform: 'uppercase',
      marginBottom: 12,
    },
    tokenCard: {
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: p.border,
      backgroundColor: p.surface,
    },
    tokenRow: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 16,
      backgroundColor: p.surface,
    },
    tokenRowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      marginRight: 12,
    },
    tokenIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: p.tokenBadgeBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    tokenIconText: {
      color: p.subtle,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
    },
    tokenMainText: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '700',
    },
    tokenSubText: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: 0,
    },
    tokenRowMeta: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    tokenRowRight: {
      alignItems: 'flex-end',
      marginRight: 12,
    },
    tokenAmountText: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '700',
    },
    tokenFiatText: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
      marginTop: 0,
    },
    tokenChevron: {
      color: '#94A3B8',
      fontSize: 20,
      fontWeight: '400',
    },
    switcherOverlay: {
      flex: 1,
      justifyContent: 'flex-start',
    },
    switcherBlur: {
      ...StyleSheet.absoluteFillObject,
    },
    switcherBackdropPressable: {
      ...StyleSheet.absoluteFillObject,
    },
    switcherSheet: {
      backgroundColor: p.surface,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      overflow: 'hidden',
      shadowColor: p.switcherShadow,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.55,
      shadowRadius: 18,
      elevation: 24,
    },
    switcherRows: {
      paddingHorizontal: 8,
      paddingTop: 8,
      paddingBottom: 0,
    },
    switcherRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      minHeight: 76,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    switcherRowFirst: {
      paddingTop: 16,
    },
    switcherRowMain: {
      flex: 1,
      marginRight: 12,
    },
    switcherRowActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      minWidth: 54,
      justifyContent: 'flex-end',
    },
    switcherRowTitle: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '700',
      marginBottom: 2,
    },
    switcherRowAddress: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
    },
    switcherSettingsButton: {
      width: 24,
      height: 24,
      alignItems: 'center',
      justifyContent: 'center',
    },
    switcherDivider: {
      height: 1,
      backgroundColor: p.divider,
      marginHorizontal: 16,
    },
    switcherAddRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 72,
      paddingHorizontal: 24,
      paddingVertical: 16,
      borderTopWidth: 1,
      borderTopColor: p.divider,
    },
    switcherAddIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 16,
    },
    switcherAddText: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    switcherMessage: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      paddingHorizontal: 24,
      paddingBottom: 16,
    },
    renameInlinePanel: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 16,
    },
    renameHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      marginBottom: 12,
    },
    renameTitle: {
      color: p.title,
      fontSize: 18,
      lineHeight: 28,
      fontWeight: '700',
    },
    renameCloseButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    renameLabel: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      marginBottom: 8,
    },
    renameInput: {
      minHeight: 50,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: p.inputBorder,
      backgroundColor: p.inputBackground,
      color: p.title,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 16,
    },
    renameSaveButton: {
      minHeight: 48,
      borderRadius: 10,
      backgroundColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    renameSaveButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    tokenDetailsContent: {
      paddingBottom: 28,
    },
    tokenDetailsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 16,
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
    },
    tokenDetailsBackButton: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tokenDetailsHeaderTitle: {
      color: p.title,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '700',
    },
    tokenDetailsHero: {
      alignItems: 'center',
      paddingHorizontal: 24,
      paddingVertical: 24,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
    },
    tokenDetailsBadge: {
      width: 62,
      height: 62,
      borderRadius: 31,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: p.tokenBadgeBg,
      marginBottom: 18,
    },
    tokenDetailsBadgeText: {
      color: p.subtle,
      fontSize: 16,
      lineHeight: 20,
      fontWeight: '700',
    },
    tokenDetailsTokenName: {
      color: p.muted,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400',
      marginBottom: 4,
    },
    tokenDetailsAmount: {
      color: p.title,
      fontSize: 36,
      lineHeight: 40,
      fontWeight: '700',
      marginBottom: 4,
    },
    tokenDetailsFiat: {
      color: p.subtle,
      fontSize: 18,
      lineHeight: 28,
      fontWeight: '400',
    },
    tokenDetailsActionsRow: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 10,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
    },
    tokenDetailsPrimaryAction: {
      flex: 1,
      minHeight: 64,
      borderRadius: 14,
      backgroundColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    tokenDetailsPrimaryActionText: {
      color: '#FFFFFF',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    tokenDetailsSecondaryAction: {
      flex: 1,
      minHeight: 64,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: p.primary,
      backgroundColor: p.surface,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    tokenDetailsSecondaryActionText: {
      color: p.primary,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
    tokenDetailsSection: {
      paddingHorizontal: 16,
      paddingTop: 16,
    },
    tokenDetailsSectionTitle: {
      color: p.subtle,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
      letterSpacing: 0.35,
      textTransform: 'uppercase',
      marginBottom: 12,
    },
    tokenDetailsInfoCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: p.border,
      backgroundColor: p.surface,
      paddingVertical: 2,
    },
    tokenDetailsInfoRow: {
      minHeight: 43,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    tokenDetailsInfoLabel: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
    },
    tokenDetailsInfoValue: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
    },
    tokenDetailsInfoValueLink: {
      color: p.primary,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    tokenDetailsEmptyText: {
      color: p.muted,
      fontSize: 16,
      lineHeight: 24,
      textAlign: 'center',
      paddingVertical: 36,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: p.border,
      backgroundColor: p.surface,
      marginBottom: 8,
    },
    tokenDetailsActivityCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: p.border,
      backgroundColor: p.surface,
      overflow: 'hidden',
      marginBottom: 8,
    },
    tokenDetailsActivityRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      gap: 10,
    },
    tokenDetailsActivityLeft: {
      flex: 1,
    },
    tokenDetailsPositiveAmount: {
      color: '#16A34A',
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '700',
      marginBottom: 2,
    },
    tokenDetailsNegativeAmount: {
      color: '#E11D48',
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '700',
      marginBottom: 2,
    },
    tokenDetailsActivityMeta: {
      color: p.muted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
    },
    tokenDetailsActivityDate: {
      color: p.muted,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
    },
    settingsContent: {
      paddingHorizontal: 0,
      paddingBottom: 32,
    },
    settingsHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
      marginBottom: 10,
    },
    settingsHeaderBackButton: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsHeaderTitle: {
      color: p.title,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '700',
    },
    settingsCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: p.border,
      backgroundColor: p.surface,
      marginHorizontal: 16,
      marginBottom: 10,
      padding: 14,
    },
    settingsCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    settingsCardHeaderIcon: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    settingsCardTitle: {
      color: p.title,
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '700',
      marginBottom: 2,
    },
    settingsCardSubtitle: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
    },
    settingsSegmentedControl: {
      flexDirection: 'row',
      gap: 8,
    },
    settingsSegmentButton: {
      flex: 1,
      minHeight: 70,
      borderRadius: 10,
      backgroundColor: p.tileBackground,
      borderWidth: 1,
      borderColor: p.tileBorder,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 9,
      gap: 6,
    },
    settingsSegmentButtonActive: {
      borderColor: '#7B70FF',
      backgroundColor: p.tileBackgroundActive,
    },
    settingsSegmentText: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
    },
    settingsSegmentTextActive: {
      color: p.title,
    },
    settingsCurrencyGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 8,
      columnGap: 8,
    },
    settingsCurrencyButton: {
      width: '48%',
      minHeight: 42,
      borderRadius: 9,
      borderWidth: 1,
      borderColor: p.tileBorder,
      backgroundColor: p.tileBackground,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 7,
    },
    settingsCurrencyButtonActive: {
      borderColor: '#7B70FF',
      backgroundColor: p.tileBackgroundActive,
    },
    settingsCurrencyText: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
    },
    settingsCurrencyTextActive: {
      color: p.title,
    },
    settingsToggleRow: {
      minHeight: 50,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    settingsActionRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    settingsRowIcon: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    settingsIconTone: {
      color: p.title,
    },
    settingsChevronTone: {
      color: p.muted,
    },
    settingsRowTitle: {
      color: p.title,
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '700',
      marginBottom: 2,
    },
    settingsRowSubtitle: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '400',
    },
    addAccountContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    addAccountHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
      marginHorizontal: -16,
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    addAccountBackButton: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    addAccountHeaderTitle: {
      color: p.title,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '700',
    },
    addAccountLabel: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      marginBottom: 8,
    },
    addAccountInput: {
      minHeight: 50,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: p.primary,
      backgroundColor: p.inputBackground,
      color: p.title,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 40,
    },
    recoveryContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    recoveryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
      marginHorizontal: -16,
      paddingHorizontal: 16,
      marginBottom: 12,
    },
    recoveryHeaderBackButton: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recoveryHeaderTitle: {
      color: p.title,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '700',
    },
    recoveryWarningCard: {
      borderRadius: 10,
      borderWidth: 1,
      borderColor: p.warningBorder,
      backgroundColor: p.warningBg,
      padding: 16,
      flexDirection: 'row',
      gap: 12,
      marginBottom: 20,
    },
    recoveryWarningTextWrap: {
      flex: 1,
    },
    recoveryWarningTitle: {
      color: p.warningText,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '700',
      marginBottom: 4,
    },
    recoveryWarningBody: {
      color: p.warningText,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '400',
    },
    twoColumnWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
      marginBottom: 24,
    },
    chip: {
      width: '31.4%',
      minHeight: 72,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: p.tileBorder,
      backgroundColor: p.chipBg,
      paddingHorizontal: 12,
      paddingVertical: 13,
    },
    chipIndex: {
      color: p.chipIndex,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '400',
      marginBottom: 4,
    },
    chipWord: {
      color: p.title,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '700',
      fontFamily: 'monospace',
    },
    recoveryCopyButton: {
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 12,
      backgroundColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 10,
    },
    recoveryCopyButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '500',
    },
    formScreenContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
    },
    formHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: p.divider,
      marginHorizontal: -16,
      paddingHorizontal: 16,
      marginBottom: 16,
    },
    formHeaderBackButton: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    formHeaderTitle: {
      color: p.title,
      fontSize: 17,
      lineHeight: 24,
      fontWeight: '700',
    },
    formLabel: {
      color: p.title,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      marginBottom: 8,
    },
    formInput: {
      minHeight: 50,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: p.inputBorder,
      backgroundColor: p.inputBackground,
      color: p.title,
      paddingHorizontal: 12,
      paddingVertical: 12,
      fontSize: 16,
      lineHeight: 24,
      marginBottom: 16,
    },
    formHelper: {
      color: p.muted,
      fontSize: 14,
      lineHeight: 20,
      marginTop: -4,
      marginBottom: 16,
    },
    formPrimaryButton: {
      minHeight: 48,
      borderRadius: 10,
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: p.primary,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 8,
    },
    formPrimaryButtonText: {
      color: '#FFFFFF',
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '600',
    },
  });
};

export const useWalletFlowStyles = () => {
  const scheme = useEffectiveColorScheme();
  return useMemo(() => buildStyles(scheme), [scheme]);
};
