# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'universalWallet' do
  config = use_native_modules!

  # Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'universalWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Add permissions configuration
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        
        # Add additional build settings for Xcode Cloud
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['VALID_ARCHS'] = 'arm64'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        
        # Handle Hermes configuration
        if target.name == 'hermes-engine'
          # Base Hermes configuration
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HERMES_ENABLE_DEBUGGER=1'
          
          # Add Hermes inspector configuration
          config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -lhermes-inspector'
          
          # Ensure the inspector is included in the build
          config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DHERMES_ENABLE_DEBUGGER=1'
          
          # Add the inspector source files
          config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) "${PODS_ROOT}/hermes-engine/destroot/include"'
          config.build_settings['LIBRARY_SEARCH_PATHS'] = '$(inherited) "${PODS_ROOT}/hermes-engine/destroot/lib"'
          
          # Additional settings for release builds
          if config.name == 'Release'
            config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DHERMES_ENABLE_DEBUGGER=1 -DHERMES_ENABLE_CDP=1'
            config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -lhermes-inspector -lhermes-cdp'
          end
        end
      end
    end
  end
end
