import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#0c0f19',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 28,
  },
  title: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 6,
  },
  subtitle: {
    color: '#9ca7bd',
    fontSize: 14,
    marginBottom: 18,
  },
  heroCard: {
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    backgroundColor: '#151a2a',
    borderWidth: 1,
    borderColor: '#232a44',
  },
  heroLabel: {
    color: '#a7b2ce',
    fontSize: 13,
    marginBottom: 8,
  },
  heroValue: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
  },
  heroSubValue: {
    color: '#97a4c4',
    fontSize: 14,
    marginTop: 6,
  },
  sectionTitle: {
    color: '#c7d2ee',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 6,
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  row: {
    backgroundColor: '#14192a',
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#232a44',
  },
  rowActive: {
    borderColor: '#615fff',
    backgroundColor: '#1a1f34',
  },
  rowTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  rowSubTitle: {
    color: '#a7b2ce',
    fontSize: 13,
    marginTop: 4,
  },
  rowValue: {
    color: '#d4dcf7',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 6,
  },
  actionButton: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#615fff',
    marginBottom: 10,
    alignItems: 'center',
  },
  actionButtonDanger: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#ad284f',
    marginBottom: 10,
    alignItems: 'center',
  },
  actionButtonSecondary: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: '#252d45',
    marginBottom: 10,
    alignItems: 'center',
  },
  actionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '600',
  },
  input: {
    borderRadius: 12,
    borderColor: '#334063',
    borderWidth: 1,
    color: '#ffffff',
    backgroundColor: '#14192a',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  helper: {
    color: '#9ca7bd',
    fontSize: 12,
    marginBottom: 12,
  },
  error: {
    color: '#ff7f9d',
    fontSize: 12,
    marginBottom: 10,
  },
  twoColumnWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  chip: {
    width: '48%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#25304a',
    backgroundColor: '#111626',
    padding: 10,
    marginBottom: 8,
  },
  chipIndex: {
    color: '#7c8ab0',
    fontSize: 11,
    marginBottom: 2,
  },
  chipWord: {
    color: '#f6f8ff',
    fontSize: 14,
    fontWeight: '600',
  },
  txAmountPositive: {
    color: '#66d49f',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 6,
  },
  txAmountNegative: {
    color: '#ff8baa',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 6,
  },
});
