import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import useEffectiveColorScheme from '../../hooks/useEffectiveColorScheme';

const palettes = {
  dark: {
    screen: '#1a1a1a',
    screenSecondary: '#2a2a2a',
    title: '#ffffff',
    subtitle: '#d0d0d0',
    heroCard: '#615fff',
    heroBorder: '#615fff',
    heroLabel: '#ddd8ff',
    heroSub: '#f4f1ff',
    section: '#b8b8b8',
    rowBg: '#252525',
    rowBorder: '#343434',
    rowDivider: '#343434',
    rowActiveBg: '#2b2b2b',
    rowTitle: '#ffffff',
    rowSub: '#9ea3ad',
    rowValue: '#ffffff',
    actionSecondary: '#3a3a3a',
    inputBorder: '#404040',
    inputBg: '#252525',
    inputText: '#ffffff',
    helper: '#b6b6b6',
    chipBorder: '#3c3c3c',
    chipBg: '#252525',
    chipIndex: '#b0b0b0',
    chipWord: '#ffffff',
    iconCircleBg: '#2f3a52',
    iconCircleText: '#c8d6f4',
    headerButtonBg: '#313131',
    headerDivider: '#343434',
    headerIcon: '#d5d5d5',
    addressText: '#e4e4e4',
    addressIcon: '#8e949f',
  },
  light: {
    screen: '#f3f4f6',
    screenSecondary: '#ffffff',
    title: '#141414',
    subtitle: '#6b7280',
    heroCard: '#615fff',
    heroBorder: '#615fff',
    heroLabel: '#ddd8ff',
    heroSub: '#f4f1ff',
    section: '#6b7280',
    rowBg: '#ffffff',
    rowBorder: '#e5e7eb',
    rowDivider: '#e5e7eb',
    rowActiveBg: '#f3f4f6',
    rowTitle: '#141414',
    rowSub: '#6b7280',
    rowValue: '#141414',
    actionSecondary: '#e5e7eb',
    inputBorder: '#d6d8de',
    inputBg: '#ffffff',
    inputText: '#141414',
    helper: '#6b7280',
    chipBorder: '#e5e7eb',
    chipBg: '#ffffff',
    chipIndex: '#6b7280',
    chipWord: '#141414',
    iconCircleBg: '#eff0f3',
    iconCircleText: '#69758e',
    headerButtonBg: '#e5e7eb',
    headerDivider: '#e5e7eb',
    headerIcon: '#6b7280',
    addressText: '#27272a',
    addressIcon: '#9ca3af',
  },
};

const buildStyles = (scheme: 'light' | 'dark') => {
  const p = palettes[scheme];

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: p.screen,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 28,
    },
    title: {
      color: p.title,
      fontSize: 28,
      fontWeight: '700',
      marginBottom: 6,
    },
    subtitle: {
      color: p.subtitle,
      fontSize: 14,
      marginBottom: 18,
    },
    heroCard: {
      borderRadius: 18,
      padding: 18,
      marginBottom: 14,
      backgroundColor: p.heroCard,
      borderWidth: 1,
      borderColor: p.heroBorder,
    },
    heroLabel: {
      color: p.heroLabel,
      fontSize: 13,
      marginBottom: 8,
    },
    heroValue: {
      color: '#ffffff',
      fontSize: 48,
      fontWeight: '700',
    },
    heroSubValue: {
      color: '#ffffff',
      fontSize: 30,
      marginTop: 6,
      fontWeight: '600',
    },
    sectionTitle: {
      color: p.section,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 12,
      marginBottom: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
    },
    row: {
      backgroundColor: p.rowBg,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 14,
      marginBottom: 10,
      borderWidth: 1,
      borderColor: p.rowBorder,
    },
    rowDivider: {
      height: 1,
      backgroundColor: p.rowDivider,
    },
    rowActive: {
      borderColor: '#615fff',
      backgroundColor: p.rowActiveBg,
    },
    rowTitle: {
      color: p.rowTitle,
      fontSize: 16,
      fontWeight: '600',
    },
    rowSubTitle: {
      color: p.rowSub,
      fontSize: 13,
      marginTop: 4,
    },
    rowValue: {
      color: p.rowValue,
      fontSize: 15,
      fontWeight: '600',
      marginTop: 6,
    },
    actionButton: {
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: '#615fff',
      marginBottom: 10,
      alignItems: 'center',
    },
    actionButtonDanger: {
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: '#ad284f',
      marginBottom: 10,
      alignItems: 'center',
    },
    actionButtonSecondary: {
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: p.actionSecondary,
      marginBottom: 10,
      alignItems: 'center',
    },
    actionText: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: '600',
    },
    input: {
      borderRadius: 12,
      borderColor: p.inputBorder,
      borderWidth: 1,
      color: p.inputText,
      backgroundColor: p.inputBg,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 10,
    },
    helper: {
      color: p.helper,
      fontSize: 12,
      marginBottom: 12,
    },
    error: {
      color: '#ff7f9d',
      fontSize: 12,
      marginBottom: 10,
    },
    twoColumnWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    chip: {
      width: '48%',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: p.chipBorder,
      backgroundColor: p.chipBg,
      padding: 10,
      marginBottom: 8,
    },
    chipIndex: {
      color: p.chipIndex,
      fontSize: 11,
      marginBottom: 2,
    },
    chipWord: {
      color: p.chipWord,
      fontSize: 14,
      fontWeight: '600',
    },
    txAmountPositive: {
      color: '#24a86b',
      fontSize: 14,
      fontWeight: '600',
      marginTop: 6,
    },
    txAmountNegative: {
      color: '#e04a73',
      fontSize: 14,
      fontWeight: '600',
      marginTop: 6,
    },
    homeHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    homeAccountButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'transparent',
      borderRadius: 0,
      paddingVertical: 0,
      paddingHorizontal: 0,
      gap: 6,
    },
    homeSettingsButton: {
      minWidth: 32,
      minHeight: 32,
      padding: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    homeAddressRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 14,
      alignSelf: 'flex-start',
      paddingVertical: 2,
      paddingRight: 6,
    },
    homeAddressText: {
      color: p.addressText,
      fontSize: 14,
      fontWeight: '600',
      fontFamily: 'monospace',
      letterSpacing: 0.2,
    },
    homeAccountText: {
      color: p.addressText,
      fontSize: 15,
      fontWeight: '600',
    },
    homeHeaderIcon: {
      color: p.headerIcon,
      fontSize: 14,
      fontWeight: '600',
    },
    homeAddressIcon: {
      color: p.addressIcon,
      fontSize: 14,
      fontWeight: '600',
    },
    homeHeaderDivider: {
      height: 1,
      backgroundColor: p.headerDivider,
      marginBottom: 16,
      marginHorizontal: -16,
    },
    homeHeroCard: {
      borderRadius: 18,
      padding: 18,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: p.heroBorder,
      overflow: 'hidden',
      position: 'relative',
      backgroundColor: p.heroCard,
    },
    homeHeroGradient: {
      ...StyleSheet.absoluteFillObject,
    },
    homeHeroLabel: {
      color: p.heroLabel,
      fontSize: 14,
      marginBottom: 8,
      fontWeight: '500',
    },
    homeHeroValue: {
      color: '#ffffff',
      fontSize: 42,
      fontWeight: '700',
      lineHeight: 48,
    },
    homeHeroCurrency: {
      color: p.heroSub,
      fontSize: 30,
      fontWeight: '600',
      marginTop: 8,
    },
    switcherOverlay: {
      flex: 1,
      justifyContent: 'flex-start',
    },
    switcherBlur: {
      ...StyleSheet.absoluteFillObject,
    },
    switcherBackdropPressable: {
      ...StyleSheet.absoluteFillObject,
    },
    switcherSheet: {
      backgroundColor: p.screenSecondary,
      borderBottomLeftRadius: 22,
      borderBottomRightRadius: 22,
      borderBottomWidth: 2,
      borderBottomColor: '#615fff',
      overflow: 'hidden',
      shadowColor: '#615fff',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.32,
      shadowRadius: 20,
      elevation: 22,
    },
    switcherRows: {
      paddingHorizontal: 18,
      paddingTop: 0,
      paddingBottom: 10,
    },
    switcherRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 12,
    },
    switcherRowFirst: {
      paddingTop: 0,
    },
    switcherRowMain: {
      flex: 1,
      marginRight: 12,
    },
    switcherRowActions: {
      minWidth: 48,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      gap: 10,
    },
    switcherRowTitle: {
      color: p.rowTitle,
      fontSize: 34 / 2,
      fontWeight: '700',
      marginBottom: 2,
    },
    switcherRowAddress: {
      color: p.rowSub,
      fontSize: 15,
      fontWeight: '600',
    },
    switcherSettingsButton: {
      width: 30,
      height: 30,
      alignItems: 'center',
      justifyContent: 'center',
    },
    switcherDivider: {
      height: 1,
      backgroundColor: p.rowDivider,
    },
    switcherAddRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingVertical: 20,
      borderTopWidth: 1,
      borderTopColor: p.rowDivider,
      backgroundColor: p.screenSecondary,
    },
    switcherAddIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#615fff',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    switcherAddText: {
      color: p.rowTitle,
      fontSize: 32 / 2,
      fontWeight: '700',
    },
    switcherMessage: {
      color: p.helper,
      fontSize: 12,
      paddingHorizontal: 18,
      paddingBottom: 14,
    },
    renameOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 20,
      backgroundColor: 'rgba(8,10,17,0.45)',
    },
    renameBackdropPressable: {
      ...StyleSheet.absoluteFillObject,
    },
    renameModalCard: {
      width: '100%',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: p.rowBorder,
      backgroundColor: p.screenSecondary,
      padding: 18,
      zIndex: 1,
    },
    renameHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
    },
    renameTitle: {
      color: p.rowTitle,
      fontSize: 22,
      fontWeight: '700',
    },
    renameCloseButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
    },
    renameLabel: {
      color: p.rowSub,
      fontSize: 13,
      fontWeight: '600',
      marginBottom: 8,
    },
    renameInput: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: p.inputBorder,
      backgroundColor: p.inputBg,
      color: p.inputText,
      paddingHorizontal: 12,
      paddingVertical: 11,
      marginBottom: 16,
    },
    renameSaveButton: {
      borderRadius: 12,
      backgroundColor: '#615fff',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
    },
    renameSaveButtonText: {
      color: '#ffffff',
      fontSize: 15,
      fontWeight: '700',
    },
    tokenCard: {
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: p.rowBorder,
      backgroundColor: p.rowBg,
    },
    tokenRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 14,
      backgroundColor: p.rowBg,
    },
    tokenRowLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      marginRight: 10,
    },
    tokenIconCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: p.iconCircleBg,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    tokenIconText: {
      color: p.iconCircleText,
      fontSize: 13,
      fontWeight: '700',
    },
    tokenMainText: {
      color: p.rowTitle,
      fontSize: 17,
      fontWeight: '700',
    },
    tokenSubText: {
      color: p.rowSub,
      fontSize: 15,
      marginTop: 2,
    },
    tokenRowRight: {
      alignItems: 'flex-end',
      marginRight: 20,
    },
    tokenRowMeta: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    tokenAmountText: {
      color: p.rowValue,
      fontSize: 17,
      fontWeight: '700',
    },
    tokenFiatText: {
      color: p.rowSub,
      fontSize: 15,
      marginTop: 2,
      fontWeight: '600',
    },
    tokenChevron: {
      color: p.addressIcon,
      marginLeft: 0,
      fontSize: 22,
      fontWeight: '600',
    },
  });
};

export const useWalletFlowStyles = () => {
  const scheme = useEffectiveColorScheme();
  return useMemo(() => buildStyles(scheme), [scheme]);
};
